### ISSUE TITLE
Values calculated are incorrect - ca. 10x smaller

### ISSUE THREAD

**Issue by madmanxxx** [kilobyte/compsize#10]
I have a freshly created BTRFS file system with only one file. It is ca. 68GB in size when compressed:
```
[root@nas ~]# df -h /dev/sdc1
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc1       932G   68G  863G   8% /mnt/m3
```
The uncompressed file is 257GB:
```
[root@nas ~]# du -h /mnt/m3/rav.img
257G    /mnt/m3/rav.img
[root@nas ~]# ls -lh /mnt/m3
total 257G
-rw-r--r-- 1 root root 257G 12-25 17:02 rav.img
```
But when I use _compsize_, I get the following result:
```
[root@nas compsize]$ ./compsize /mnt/m3/rav.img
Type       Perc     Disk Usage   Uncompressed Referenced
TOTAL       40%       10G          26G          26G
none       100%      3.0G         3.0G         3.0G
zstd        32%      7.6G          23G          23G

```

Environment:
 - Arch Linux, kernel: 4.14.8-1-ARCH
 - btrfs-progs: 4.14-2
- compsize: 33c07cb9f18cc386146d9ffd27aee15d4cb6edca

**Comment by roiderats** [comment]
I was almost sure about wrong reporting with my 240 and 120 GB disk-image files, reported so small(like 9GB if I remember correctly) that maybe there's bytes worth of highest bits lost somewhere. Can't get into studying that now thou.

**Comment by kilobyte** [comment]
@roiderats: is this with or without the fix I applied two weeks ago?

The value of 24GB shows only on fully compressed, unfragmented files — having any non-compressed extents (the original reporter had 3G of them) moves the max up, fragmentation moves it down.

**Comment by roiderats** [comment]
My observation was atleast two weeks ago. Status closed=fine
