### ISSUE TITLE
SEARCH_V2: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by andras-kiss** [kilobyte/compsize#12]
I'm not sure if this is the right place to post (possible) bugs. Anyway when I try to run compsize on root or my home folder, I get this error message:

`akiss@buster:~$ su`
`Password:`
`root@buster:/home/akiss# ./compsize/compsize .`
`SEARCH_V2: Inappropriate ioctl for device`
`root@buster:/home/akiss#`

When I run it on a subfolder, it works as expected:

`root@buster:/home/akiss# ./compsize/compsize .steam`
`Processed 34050 files, 206016 regular extents (206274 refs), 10770 inline.`
`Type       Perc     Disk Usage   Uncompressed Referenced  `
`TOTAL       65%       23G          35G          35G      ` 
`none       100%       12G          12G          12G     `
`zstd        45%       10G          22G          22G       `
`root@buster:/home/akiss#`

I have an ext4 boot partition mounted at /boot, and a samba share mounted in my home folder.

`root@buster:/home/akiss# uname -a`
`Linux buster 4.14.0-2-amd64 #1 SMP Debian 4.14.7-1 (2017-12-22) x86_64 GNU/Linux`

**Comment by kilobyte** [comment]
Yeah, the handling of non-btrfs filesystems is not as good as it should be.

"Inappropriate ioctl for device" still sounds better than "Not a typewriter" this ioctl would say a while ago (its #define is still named ENOTTY), but an expected error should provide a more obvious message.

I still think that failing immediately when given a non-btrfs initial directory is a good idea, as most of the time all the recursive traversal would be pointless.  Should probably have an override for your use case, though.

Any advice?

**Comment by andras-kiss** [comment]
Thank you for the response. I'm not a developer at all (at least not programmer). I've unmounted the samba share in my home directory (subfolder in home: /home/akiss/share), and compsize produces a report. Yes, maybe it would be useful if compsize ignored any non-brtfs subfolder, or maybe inculde that in the report.

I think it's really cool to see how much smaller data becomes with compression. I hope it will be in the kernel soon as part of brtfs-progs.

**Comment by kilobyte** [comment]
The error message is unhelpful enough that it needs fixing.
