### ISSUE TITLE
Don't die on EACCESS

### ISSUE THREAD

**Issue by comio** [kilobyte/compsize#16]
Hi,

your tool is very useful. I have just a request, can you avoid to call die() when errno==EACCES?
I suppose that we can just ignore the failing open() and continue.
(I will provide a PR if you need)

ciao

luigi

**Comment by kilobyte** [comment]
Good catch, even though we're root, an user can have a sshfs mount, etc.  Fixed.

Are there other errors you'd think should be non-fatal as well?
