### ISSUE TITLE
Add support for signals

### ISSUE THREAD

**Issue by fredrike** [kilobyte/compsize#19]
It would be great if you could support signals to show status of the investigated files so far..

Like the SIGUSR1 on `dd` https://askubuntu.com/a/215521.

Currently running on a medium sized directory (~700GB) for a couple of hours..

**Comment by kilobyte** [comment]
Good idea.  I wanted to make it interactive as something akin to **ncdu**, but it doesn't seem like I'll have the tuits anytime soon...

I guess it could be better to instead print progress as the directory is scanned (assuming the output is not redirected).  But having both the progress and signals can't hurt.
