### ISSUE TITLE
SZ_16M missing

### ISSUE THREAD

**Issue by GrahamCobb** [kilobyte/compsize#2]
Latest version doesn't compile here (debian buster)...

cc -Wall  -c -o compsize.o compsize.c
compsize.c:30:18: error: ‘SZ_16M’ undeclared here (not in a function)
     uint8_t  buf[SZ_16M]; // hardcoded kernel's limit

**Comment by kilobyte** [comment]
I can't seem to reproduce -- builds for me in a fresh minimal buster chroot with nothing but build-essential and btrfs-progs installed.

**Comment by kilobyte** [comment]
On the other hand, on stretch it fails the way you describe.  Apparently your buster is outdated, but as most users have stretch or older (or other distros' equivalent), the problem is real.

Fixed, thanks for letting me know!
