### ISSUE TITLE
File sizes / output has massivly changed with latest version

### ISSUE THREAD

**Issue by disaster123** [kilobyte/compsize#21]
I was running caed4fdcd888467ddabd1b964b7737c0a0b050c8 for a long time. I updated to latest version but values have massivly changed:
caed4fdcd888467ddabd1b964b7737c0a0b050c8:
```
Processed 62 files.
Type       Perc     Disk Usage   Uncompressed Referenced  
Data        69%       72G         104G         141G       
none       100%       37G          37G          46G       
zstd        52%       34G          66G          95G       
```

Current HEAD:
```
Processed 62 files, 1347823 regular extents (1622359 refs), 33 inline.
Type       Perc     Disk Usage   Uncompressed Referenced  
TOTAL       76%      179G         235G         273G       
none       100%      106G         106G         116G       
zstd        56%       73G         128G         157G       
```

What has happened?

**Comment by constantoverride** [comment]
Just guessing, but maybe this: https://github.com/kilobyte/compsize/commit/01ad3d03ba12d2ecd24e349be6f0ab5b905fb72d

**Comment by kilobyte** [comment]
Judging from the size of your files, it's almost certainly this.  It was a bug, sorry — the old version capped large files.

**Comment by kilobyte** [comment]
Closing; please reopen if you suspect anything else than that old bug.

**Comment by disaster123** [comment]
@kilobyte ok thanks one last question would it be possible to skip extents already referenced by another file? This would make it possible to show total real size of multiple snapshots
