### ISSUE TITLE
Show sparse usage. 

### ISSUE THREAD

**Issue by Gatak** [kilobyte/compsize#30]
It would be good if sparse holes are shown as it's own row instead of baked in with "none".

```
# touch file
# fallocate -l 100M file
# compsize file
Type       Perc     Disk Usage   Uncompressed Referenced
TOTAL      100%      100M         100M         100M
none       100%      100M         100M         100M
```

**Comment by kilobyte** [comment]
These are no holes — compsize doesn't display those at all, otherwise a single 1PB file would dwarf everything else.  But handling preallocated extents as if they were a separate compression type is reasonable.
