### ISSUE TITLE
Change the name to btrfs-compsize

### ISSUE THREAD

**Issue by htot** [kilobyte/compsize#33]
Or something similar.

This will enable the user to find the command when using `btrfs<TAB completion>` and it will be among the other useful btrfs tools.

**Comment by kilobyte** [comment]
I'd rather go the other direction — more and more filesystems grow capabilities where space used is different than a plain number of pages.  XFS already has reflinks, f2fs has compression and a plan for reflinks, etc.

And other than the ioctl needed to get that data, the user-facing behaviour is same: space(A+B) may be ≤ space(A)+space(B) for reflinks, etc.

**Comment by htot** [comment]
You mean you would rather add support for XFS, f2fs etc. and keep the name?

**Comment by kilobyte** [comment]
Yeah, preferably abstracting the internal details.

**Comment by htot** [comment]
That sound like a rather bigger job :-)
