### ISSUE TITLE
compsize could be more user-friendly (from an enduser perspective)

### ISSUE THREAD

**Issue by ferdnyc** [kilobyte/compsize#37]
It's [been proposed](https://fedoraproject.org/wiki/Changes/BtrfsTransparentCompression) that for Fedora 34, transparent compression be enabled by default on btrfs volumes, and `compsize` be offered as the standard tool for examining file compression on zstd-compressed volumes.

Given that `compsize` would then be an enduser tool, including potentially for lay users, [I felt](https://pagure.io/fedora-btrfs/project/issue/5) that it might benefit from a few user-friendliness enhancements. Specifically:

1. It doesn't currently accept standard `-h` / `--help` arguments
    ```sh
    $ compsize --help
    compsize: unrecognized option '--help'
    ```
2. It doesn't explain anything about what it is or what it does, in its default help text:
    ```sh
    $ compsize
    Usage: compsize file-or-dir1 [file-or-dir2 ...]
    ```
3. The man page gets very technical, and fairly quickly. By the second paragraph it's discussing partial extents and multiply-reflinked files. Way over the head of most users just looking to examine compression ratios, and nothing they really _need_ to be concerned with either.

**Comment by ferdnyc** [comment]
> 1. It doesn't currently accept standard `-h` / `--help` arguments
>    ```shell
>    $ compsize --help
>    compsize: unrecognized option '--help'
>    ```

Heh. Never mind, I see that first one has already been addressed in the repo.

In that case, I'd like to request/suggest a new release. Fedora is still packaging the 1.3 release, which is getting a bit out of date at this point (and lacks crucial enhancements like `-h`/`--help`, `-b`/`--bytes`, and `-x`/`--one-file-system`).

**Comment by kilobyte** [comment]
Hi, I've edited the man page a bit.  Does it sound more palatable to new users?

Would you have some more comments?  If not, I'll cut a new release.
