### ISSUE TITLE
No install instructions -- how to build?

### ISSUE THREAD

**Issue by romanrm** [kilobyte/compsize#5]
Trying to run 'make':

```
# make
cc -Wall  -c -o compsize.o compsize.c
compsize.c: In function ‘main’:
compsize.c:301:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int t=0; t<MAX_ENTRIES; t++)
     ^
compsize.c:301:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
compsize.c:328:14: error: redefinition of ‘t’
     for (int t=0; t<MAX_ENTRIES; t++)
              ^
compsize.c:301:14: note: previous definition of ‘t’ was here
     for (int t=0; t<MAX_ENTRIES; t++)
              ^
compsize.c:328:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int t=0; t<MAX_ENTRIES; t++)
     ^
Makefile:11: recipe for target 'compsize.o' failed
make: *** [compsize.o] Error 1

# cc --version
cc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Could you please describe the prerequisites or install instructions in the README file.

Thanks

**Comment by kilobyte** [comment]
Your compiler is configured to use an ancient C standard by default.  But, *btrfs-progs* themselves use that version too, thus I've removed new-style declarations.

As for other prerequisites, the only required piece besides the usual C toolchain are btrfs userspace headers, shipped with *btrfs-progs*.  I've added this to the README.

**Comment by romanrm** [comment]
"Same as btrfs-progs" is not helpful at all for those who has no need or interest to build btrfs-progs and just wants to build this tool.

**Comment by kilobyte** [comment]
Right, that's why I mentioned this only in my response here -- README has no such words.  My aim is to seek inclusion in btrfs-progs once this tool matures, that's why I regressed to an old and smelly version of C instead of requesting something non-ancient.

**Comment by romanrm** [comment]
For inclusion in btrfs-progs, it would be logical to extend "btrfs filesystem du" instead of a separate tool.

**Comment by kilobyte** [comment]
An option to "f du" would be nice, yeah.

But the code isn't complete yet: it's broken on 32-bit for filesystems above 8TB; I know of at least one case where it gives a greatly incorrect answer; it'd be nice to have a measure of wasted space in pinned extents.
