### ISSUE TITLE
Readme is unclear regarding the meaning of the lines "Data", "none", etcetera.

### ISSUE THREAD

**Issue by ProBackup-nl** [kilobyte/compsize#9]
```
# compsize /mnt/sda2/Backups.backupdb/d2/2017-12-17-211627
Processed 24766 files, 20583 regular extents (22801 refs), 12848 inline.
Type       Perc     Disk Usage   Uncompressed Referenced
Data        31%      471M         1.4G         1.7G
none       100%      126M         126M         126M
zstd        25%      344M         1.3G         1.5G
```

Now I am wondering: what is "Data", "none" and "zstd"?
Or what are the differences between them.

After reading https://github.com/kilobyte/compsize/blob/master/README.md the clue is still missing.

**Comment by kilobyte** [comment]
The man page has a more detailed explanation, but you're right, as README mentions all other fields, it should say what's "Type" as well.

I added a line, is this enough?

**Comment by ProBackup-nl** [comment]
Even after reading https://github.com/kilobyte/compsize/blob/master/compsize.8 it is still not clear to me what the difference between "Data" and "none" is.

It feels like "none" means "not compressed". Then 100% is redundant for that line.
Also redundant is the column header "Perc" and value "..%" -> "C.ratio" (value=1-current printed %)), and "Type"  means "Compression type".

Still no clue what "compression type = Data" means.

**Comment by ProBackup-nl** [comment]
When "Data" is a total, it at least be at the bottom, below the lines it sums.
Preferably marked by a dashed line:

```
Type       Ratio     Disk Usage   Uncompressed Referenced
none          0%     1.4G         1.4G         1.7G
zstd         57%     574K         1.2M         1.2M
---------  -----  -------      -------      -------
total         1%     1.4G         1.4G         1.7G
```
